user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

# FosUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
