<?php

namespace Proxies\__CG__\Ct\Service\MetierManagerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtVehicule extends \Ct\Service\MetierManagerBundle\Entity\CtVehicule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcCylindre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcPuissance', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcPoidsVide', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcChargeUtile', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcPoidsTotalCharge', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcHauteur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcLargeur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcLongueur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcNumSerie', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcNumMoteur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcCreated', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcProvenance', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcType', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'ctGenre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'ctMarque'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcCylindre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcPuissance', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcPoidsVide', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcChargeUtile', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcPoidsTotalCharge', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcHauteur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcLargeur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcLongueur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcNumSerie', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcNumMoteur', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcCreated', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcProvenance', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'vhcType', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'ctGenre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtVehicule' . "\0" . 'ctMarque'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtVehicule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcCylindre($vhcCylindre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcCylindre', [$vhcCylindre]);

        return parent::setVhcCylindre($vhcCylindre);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcCylindre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcCylindre', []);

        return parent::getVhcCylindre();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcPuissance($vhcPuissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcPuissance', [$vhcPuissance]);

        return parent::setVhcPuissance($vhcPuissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcPuissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcPuissance', []);

        return parent::getVhcPuissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcPoidsVide($vhcPoidsVide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcPoidsVide', [$vhcPoidsVide]);

        return parent::setVhcPoidsVide($vhcPoidsVide);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcPoidsVide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcPoidsVide', []);

        return parent::getVhcPoidsVide();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcChargeUtile($vhcChargeUtile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcChargeUtile', [$vhcChargeUtile]);

        return parent::setVhcChargeUtile($vhcChargeUtile);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcChargeUtile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcChargeUtile', []);

        return parent::getVhcChargeUtile();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcHauteur($vhcHauteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcHauteur', [$vhcHauteur]);

        return parent::setVhcHauteur($vhcHauteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcHauteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcHauteur', []);

        return parent::getVhcHauteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcLargeur($vhcLargeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcLargeur', [$vhcLargeur]);

        return parent::setVhcLargeur($vhcLargeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcLargeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcLargeur', []);

        return parent::getVhcLargeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcLongueur($vhcLongueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcLongueur', [$vhcLongueur]);

        return parent::setVhcLongueur($vhcLongueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcLongueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcLongueur', []);

        return parent::getVhcLongueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcNumSerie($vhcNumSerie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcNumSerie', [$vhcNumSerie]);

        return parent::setVhcNumSerie($vhcNumSerie);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcNumSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcNumSerie', []);

        return parent::getVhcNumSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcNumMoteur($vhcNumMoteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcNumMoteur', [$vhcNumMoteur]);

        return parent::setVhcNumMoteur($vhcNumMoteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcNumMoteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcNumMoteur', []);

        return parent::getVhcNumMoteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcCreated($vhcCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcCreated', [$vhcCreated]);

        return parent::setVhcCreated($vhcCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcCreated', []);

        return parent::getVhcCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcProvenance($vhcProvenance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcProvenance', [$vhcProvenance]);

        return parent::setVhcProvenance($vhcProvenance);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcProvenance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcProvenance', []);

        return parent::getVhcProvenance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtGenre(\Ct\Service\MetierManagerBundle\Entity\CtGenre $ctGenre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtGenre', [$ctGenre]);

        return parent::setCtGenre($ctGenre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtGenre', []);

        return parent::getCtGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtMarque(\Ct\Service\MetierManagerBundle\Entity\CtMarque $ctMarque = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtMarque', [$ctMarque]);

        return parent::setCtMarque($ctMarque);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtMarque', []);

        return parent::getCtMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcType($vhcType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcType', [$vhcType]);

        return parent::setVhcType($vhcType);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcType', []);

        return parent::getVhcType();
    }

    /**
     * {@inheritDoc}
     */
    public function setVhcPoidsTotalCharge($vhcPoidsTotalCharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVhcPoidsTotalCharge', [$vhcPoidsTotalCharge]);

        return parent::setVhcPoidsTotalCharge($vhcPoidsTotalCharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhcPoidsTotalCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhcPoidsTotalCharge', []);

        return parent::getVhcPoidsTotalCharge();
    }

}
