anomalie_index:
    path:     /
    defaults: { _controller: "AdminBundle:CtAnomalie:index" }
    methods:  GET

anomalie_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CtAnomalie:new" }
    methods:  [GET, POST]

anomalie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:CtAnomalie:edit" }
    methods:  [GET, POST]

anomalie_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:CtAnomalie:update" }
    methods:  [POST, PUT]

anomalie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:CtAnomalie:delete" }
    methods:  [GET, DELETE]

anomalie_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:CtAnomalie:deleteGroup" }
    methods:  POST