genre_index:
    path:     /
    defaults: { _controller: "AdminBundle:CtGenre:index" }
    methods:  GET

genre_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CtGenre:new" }
    methods:  [GET, POST]

genre_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:CtGenre:edit" }
    methods:  [GET, POST]

genre_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:CtGenre:update" }
    methods:  [POST, PUT]

genre_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:CtGenre:delete" }
    methods:  [GET, DELETE]

genre_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:CtGenre:deleteGroup" }
    methods:  POST