motif_tarif_index:
    path:     /
    defaults: { _controller: "AdminBundle:CtMotifTarif:index" }
    methods:  GET

motif_tarif_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CtMotifTarif:new" }
    methods:  [GET, POST]

motif_tarif_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:CtMotifTarif:edit" }
    methods:  [GET, POST]

motif_tarif_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:CtMotifTarif:update" }
    methods:  [POST, PUT]

motif_tarif_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:CtMotifTarif:delete" }
    methods:  [GET, DELETE]

motif_tarif_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:CtMotifTarif:deleteGroup" }
    methods:  POST