type_reception_index:
    path:     /
    defaults: { _controller: "AdminBundle:CtTypeReception:index" }
    methods:  GET

type_reception_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CtTypeReception:new" }
    methods:  [GET, POST]

type_reception_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:CtTypeReception:edit" }
    methods:  [GET, POST]

type_reception_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:CtTypeReception:update" }
    methods:  [POST, PUT]

type_reception_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:CtTypeReception:delete" }
    methods:  [GET, DELETE]

type_reception_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:CtTypeReception:deleteGroup" }
    methods:  POST