utilisation_index:
    path:     /
    defaults: { _controller: "AdminBundle:CtUtilisation:index" }
    methods:  GET

utilisation_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CtUtilisation:new" }
    methods:  [GET, POST]

utilisation_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:CtUtilisation:edit" }
    methods:  [GET, POST]

utilisation_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:CtUtilisation:update" }
    methods:  [POST, PUT]

utilisation_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:CtUtilisation:delete" }
    methods:  [GET, DELETE]

utilisation_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:CtUtilisation:deleteGroup" }
    methods:  POST