<?php

namespace Proxies\__CG__\Ct\Service\MetierManagerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtImprimeTechUse extends \Ct\Service\MetierManagerBundle\Entity\CtImprimeTechUse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctBordereau', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctCentre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctImprimeTech', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctControle', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctUser', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ituNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ituUsed', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ituMotifUsed', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'createdAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctBordereau', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctCentre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctImprimeTech', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctControle', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ctUser', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ituNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ituUsed', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'ituMotifUsed', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'createdAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtImprimeTechUse' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtImprimeTechUse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtBordereau(\Ct\Service\MetierManagerBundle\Entity\CtBordereau $ctBordereau = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtBordereau', [$ctBordereau]);

        return parent::setCtBordereau($ctBordereau);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtBordereau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtBordereau', []);

        return parent::getCtBordereau();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtCentre(\Ct\Service\MetierManagerBundle\Entity\CtCentre $ctCentre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtCentre', [$ctCentre]);

        return parent::setCtCentre($ctCentre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtCentre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtCentre', []);

        return parent::getCtCentre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtImprimeTech(\Ct\Service\MetierManagerBundle\Entity\CtImprimeTech $ctImprimeTech = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtImprimeTech', [$ctImprimeTech]);

        return parent::setCtImprimeTech($ctImprimeTech);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtImprimeTech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtImprimeTech', []);

        return parent::getCtImprimeTech();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtControle($ctControle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtControle', [$ctControle]);

        return parent::setCtControle($ctControle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtControle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtControle', []);

        return parent::getCtControle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtUser(\Ct\Service\UserBundle\Entity\User $ctUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtUser', [$ctUser]);

        return parent::setCtUser($ctUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtUser', []);

        return parent::getCtUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setItuNumero($ituNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItuNumero', [$ituNumero]);

        return parent::setItuNumero($ituNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getItuNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItuNumero', []);

        return parent::getItuNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setItuUsed($ituUsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItuUsed', [$ituUsed]);

        return parent::setItuUsed($ituUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getItuUsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItuUsed', []);

        return parent::getItuUsed();
    }

    /**
     * {@inheritDoc}
     */
    public function setItuMotifUsed($ituMotifUsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItuMotifUsed', [$ituMotifUsed]);

        return parent::setItuMotifUsed($ituMotifUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getItuMotifUsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItuMotifUsed', []);

        return parent::getItuMotifUsed();
    }

    /**
     * {@inheritDoc}
     */
    public function setItuCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItuCreatedAt', [$createdAt]);

        return parent::setItuCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getItuCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItuCreatedAt', []);

        return parent::getItuCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setItuUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItuUpdatedAt', [$updatedAt]);

        return parent::setItuUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getItuUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItuUpdatedAt', []);

        return parent::getItuUpdatedAt();
    }

}
