<?php

namespace Proxies\__CG__\Ct\Service\MetierManagerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtBordereau extends \Ct\Service\MetierManagerBundle\Entity\CtBordereau implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'refExpr', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'dateRefExpr', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blDebutNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blFinNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'ctCentre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'ctImprimeTech', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'ctUser', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blCreatedAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blUpdatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'refExpr', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'dateRefExpr', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blDebutNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blFinNumero', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'ctCentre', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'ctImprimeTech', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'ctUser', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blCreatedAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtBordereau' . "\0" . 'blUpdatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtBordereau $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefExpr($refExpr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefExpr', [$refExpr]);

        return parent::setRefExpr($refExpr);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefExpr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefExpr', []);

        return parent::getRefExpr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRefExpr($dateRefExpr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRefExpr', [$dateRefExpr]);

        return parent::setDateRefExpr($dateRefExpr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRefExpr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRefExpr', []);

        return parent::getDateRefExpr();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlNumero($blNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlNumero', [$blNumero]);

        return parent::setBlNumero($blNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlNumero', []);

        return parent::getBlNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtCentre($ctCentre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtCentre', [$ctCentre]);

        return parent::setCtCentre($ctCentre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtCentre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtCentre', []);

        return parent::getCtCentre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtImprimeTech(\Ct\Service\MetierManagerBundle\Entity\CtImprimeTech $ctImprimeTech = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtImprimeTech', [$ctImprimeTech]);

        return parent::setCtImprimeTech($ctImprimeTech);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtImprimeTech()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtImprimeTech', []);

        return parent::getCtImprimeTech();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtUser(\Ct\Service\UserBundle\Entity\User $ctUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtUser', [$ctUser]);

        return parent::setCtUser($ctUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtUser', []);

        return parent::getCtUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlDebutNumero($blDebutNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlDebutNumero', [$blDebutNumero]);

        return parent::setBlDebutNumero($blDebutNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlDebutNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlDebutNumero', []);

        return parent::getBlDebutNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlFinNumero($blFinNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlFinNumero', [$blFinNumero]);

        return parent::setBlFinNumero($blFinNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlFinNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlFinNumero', []);

        return parent::getBlFinNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlCreatedAt($blCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlCreatedAt', [$blCreatedAt]);

        return parent::setBlCreatedAt($blCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlCreatedAt', []);

        return parent::getBlCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlUpdatedAt($blUpdatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlUpdatedAt', [$blUpdatedAt]);

        return parent::setBlUpdatedAt($blUpdatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlUpdatedAt', []);

        return parent::getBlUpdatedAt();
    }

}
