<?php

namespace Proxies\__CG__\Ct\Service\MetierManagerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtCentre extends \Ct\Service\MetierManagerBundle\Entity\CtCentre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrNom', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrCode', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrCreatedAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrUpdatedAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctProvince'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrNom', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrCode', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrCreatedAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctrUpdatedAt', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtCentre' . "\0" . 'ctProvince'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtCentre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtrNom($ctrNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtrNom', [$ctrNom]);

        return parent::setCtrNom($ctrNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtrNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtrNom', []);

        return parent::getCtrNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtrCode($ctrCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtrCode', [$ctrCode]);

        return parent::setCtrCode($ctrCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtrCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtrCode', []);

        return parent::getCtrCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtrCreatedAt($ctrCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtrCreatedAt', [$ctrCreatedAt]);

        return parent::setCtrCreatedAt($ctrCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtrCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtrCreatedAt', []);

        return parent::getCtrCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtrUpdatedAt($ctrUpdatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtrUpdatedAt', [$ctrUpdatedAt]);

        return parent::setCtrUpdatedAt($ctrUpdatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtrUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtrUpdatedAt', []);

        return parent::getCtrUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtProvince(\Ct\Service\MetierManagerBundle\Entity\CtProvince $ctProvince = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtProvince', [$ctProvince]);

        return parent::setCtProvince($ctProvince);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtProvince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtProvince', []);

        return parent::getCtProvince();
    }

}
