<?php

namespace Proxies\__CG__\Ct\Service\MetierManagerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtDroitPtac extends \Ct\Service\MetierManagerBundle\Entity\CtDroitPtac implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'dpPrixMin', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'dpPrixMax', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'dpDroit', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'ctGenreCategorie', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'ctTypeDroitPtac'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'id', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'dpPrixMin', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'dpPrixMax', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'dpDroit', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'ctGenreCategorie', '' . "\0" . 'Ct\\Service\\MetierManagerBundle\\Entity\\CtDroitPtac' . "\0" . 'ctTypeDroitPtac'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtDroitPtac $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpPrixMin($dpPrixMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpPrixMin', [$dpPrixMin]);

        return parent::setDpPrixMin($dpPrixMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpPrixMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpPrixMin', []);

        return parent::getDpPrixMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpPrixMax($dpPrixMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpPrixMax', [$dpPrixMax]);

        return parent::setDpPrixMax($dpPrixMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpPrixMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpPrixMax', []);

        return parent::getDpPrixMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpDroit($dpDroit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpDroit', [$dpDroit]);

        return parent::setDpDroit($dpDroit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpDroit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpDroit', []);

        return parent::getDpDroit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtGenreCategorie(\Ct\Service\MetierManagerBundle\Entity\CtGenreCategorie $ctGenreCategorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtGenreCategorie', [$ctGenreCategorie]);

        return parent::setCtGenreCategorie($ctGenreCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtGenreCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtGenreCategorie', []);

        return parent::getCtGenreCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtTypeDroitPtac(\Ct\Service\MetierManagerBundle\Entity\CtTypeDroitPtac $ctTypeDroitPtac = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtTypeDroitPtac', [$ctTypeDroitPtac]);

        return parent::setCtTypeDroitPtac($ctTypeDroitPtac);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtTypeDroitPtac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtTypeDroitPtac', []);

        return parent::getCtTypeDroitPtac();
    }

}
